config/routes.rb
Rails.application.routes.draw do
  root 'info_page#home'
  get 'info_page/home'
  get 'info_page/about'

  devise_for :users

  resources :correntista do
    resources :conta
  end

  resources :conta do
    resources :saque
    resources :deposito do
      get 'transfer', on: :new
    end
    get 'extrato', :only => [:show]
  end
  resources :saque, :only => [:show]
  resources :deposito, :only => [:show]

end

app/models/conta.rb
class Conta < ActiveRecord::Base
  belongs_to :correntista
  has_many :saque
  has_many :deposito, foreign_key: "conta_destino_id"
  before_destroy :inativate
  before_create :corrigeValor
  # after_validation :corrigeVa/lor

  # validates_numericality_of :saldoProvisorio, message: ("Deve ser número ou o valor ou 0") unless nil
  validates_format_of :saldoProvisorio, :allow_blank => true, :with => /(?:\d*.+,)?\d+/i, :message => "Não pode ficar em branco nem ser letras. Aceita (,) ou (.)"


  attr_accessor :saldoProvisorio

  scope :ativa, ->{
    where(flag_ativo: "S")
  }

  scope :qtdAtiva, ->{
    where(flag_ativo: "S").count
  }

  def before_destroy
    if saldo == 0
      self.saldoProvisorio = 0
      self.flag_ativo = 'N'
      return true
    end
    errors.add :base, "thiago thiago"
    # or errors.add_to_base in Rails 2
    false
  end

  def corrigeValor
    self.saldo = self.saldoProvisorio.gsub(/,/){'.'}.to_d
  end

  def self.retornaContasAtivas
    ativa.each{ |x| p x.id }
  end

  def self.retornaContasAtivasSemContaOrigem(conta)
    retorno = []
    ativa.where.not(:id => conta).order(:id).each do |x|
      retorno << x.id
    end
    retorno
  end

  def extratoSaque
    self.saque
  end

  def extratoDeposito
    self.deposito.deposito
  end

  def extratoTransferenciaRecebidas
    self.deposito.transferenciaRecebidas
  end

  def extratoTransferenciaOriginadas
    Deposito.where("conta_origem_id = ?", self.id)
  end

end

app/controllers/conta_controller.rb
class ContaController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conta, only: [:show, :edit, :update, :destroy ]
  before_action :set_extrato, only: [:extrato]
  before_action :set_contas, only: [:index]

  # GET /conta
  # GET /conta.json
  def index
  end

  def show
    # GET /conta/1
    # GET /conta/1.json
  end

  # GET /conta/extrato/1
  # GET /conta/extrato/1.json
  def extrato

  end


  # GET /conta/new
  def new
    @correntista = Correntista.find(params[:correntista_id])
    @conta = @correntista.contas.new
  end

  # GET /conta/1/edit
  def edit
  end

  # POST /conta
  # POST /conta.json
  def create
    @conta = Conta.new(conta_params)

    # @conta.correntista = Correntista.find(params[:id])
    respond_to do |format|
      if @conta.save
        format.html { redirect_to correntista_conta_index_path, notice: 'Conta was successfully created.' }
        format.json { render :show, status: :created, location: @conta }
      else
        format.html { render :new }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conta/1
  # PATCH/PUT /conta/1.json
  def update
    respond_to do |format|
      if @conta.update(conta_params)
        format.html { redirect_to @conta, notice: 'Conta was successfully updated.' }
        format.json { render :show, status: :ok, location: @conta }
      else
        format.html { render :edit }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conta/1
  # DELETE /conta/1.json
  def destroy
    @correntista = Correntista.find([current_user.correntista_id])
    @conta = Conta.find(params[:id])
    if @conta.before_destroy
      @conta.save
        respond_to do |format|
          format.html { redirect_to correntista_conta_index_path(current_user), notice: 'Conta desativada corretamente.'  }
          format.json { head :ok }
      end
    else
      respond_to do |format|
        format.html { redirect_to correntista_path(@correntista, @conta.errors) }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_conta
    if User.find(current_user.id).correntista.contas.where(:id => params[:id]).present?
      @conta = Conta.find(params[:id])
    else
      flash[:alert] = "A conta digitada na url não existe ou não te pertence, por favor não digite na url."
      redirect_to correntista_url
    end
  end

  def set_contas
    @conta = User.find(current_user.id).correntista.contas
  end

  def set_extrato
    @conta = Conta.find(params[:conta_id])
    # conta = @conta./
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def conta_params
    params.require(:conta).permit(:correntista_id, :flag_ativo, :created_at, :updated_at, :saldo, :saldoProvisorio)
  end
end

app/helpers/conta_helper.rb
module ContaHelper
end

app/views/conta/_form.html.erb
<%#= form_for(@conta) do |f| %>
<%= form_for([:correntista, @conta]) do |f| %>
  <% if @conta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conta.errors.count, "error") %> prohibited this conta from being saved:</h2>

      <ul>
      <% @conta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :correntista_id %><br>
    <%= f.text_field :correntista_id,:readonly => true %>
  </div>
  <div class="field">
    <%= f.label :flag_ativo %><br>
    <%= f.text_field :flag_ativo, :readonly => true %>
  </div>

  <div class="field">
    <%= f.hidden_field :updated_at %>
  </div>
  <div class="field">
    <%= f.label :saldo %><br>
    <%= f.text_field :saldoProvisorio, id: :valorField , maxlength: 18 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%#= f.label :created_at %><br>
    <%#= f.label DateTime.current.to_formatted_s(:rfc822), :readonly => true %>
  </div>
<% end %>

app/views/conta/edit.html.erb
<h1>Editing Conta</h1>

<%= render 'form' %>

<%= link_to 'Show', @conta %> |
<%= link_to 'Back', conta_index_path %>

app/views/conta/extrato.html.erb
<%= link_to conta_path(@conta), class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12">
    <h2>Extrato</h2>
    <span class="col-md-4">
      <strong>Conta:</strong>
      <%= @conta.id %>
    </span>
    <span class="col-md-4">
      <strong class="green">Saldo:</strong>
      R$ <%= @conta.saldo %>
    </span>
    <span class="col-md-4">
      Data: <strong><%= Date.today %> </strong>
    </span>
  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Saques</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Data e Horário</th>
                <th>Valor</th>
              </tr>
            </thead>
            <tbody>
              <% @conta.extratoSaque.each do |extrato| %>
              <tr class="danger">
                <td></td>
                <td><%= extrato.created_at.strftime("%m/%d/%Y - %H:%M:%S") %></td>
                <td>R$ - <%= extrato.valor %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Depósitos</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Data e Horário</th>
                <th>Valor</th>
              </tr>
            </thead>
            <tbody>
              <% @conta.extratoDeposito.each do |extrato| %>
              <tr class="success">
                <td></td>
                <td><%= extrato.created_at.strftime("%m/%d/%Y - %H:%M:%S") %></td>
                <td>R$ + <%= extrato.valor %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-12">
    <!--    Context Classes  -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Tansferências Recebidas</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>De (Conta Origem)</th>
                <th>Para (Conta Destino)</th>
                <th>Data e Horário</th>
                <th>Valor</th>
              </tr>
            </thead>
            <tbody>
              <% @conta.extratoTransferenciaRecebidas.each do |extrato| %>
              <tr class="info">
                <td><%= extrato.conta_origem_id %></td>
                <td><%= extrato.conta_destino_id %></td>
                <td><%= extrato.created_at.strftime("%m/%d/%Y - %H:%M:%S") %></td>
                <td>R$ + <%= extrato.valor %></td>
                <!-- <td>R$ <%= extrato.taxa %></td> -->
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!--  end  Context Classes  -->
  </div>
</div>
<!-- End  Hover Rows  -->
<hr>
<div class="row">
  <div class="col-md-12">
    <!--    Context Classes  -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Tansferências Realizadas</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>De (Conta Origem)</th>
                <th>Para (Conta Destino)</th>
                <th>Data e Horário</th>
                <th>Valor</th>
                <th>Taxa</th>
              </tr>
            </thead>
            <tbody>
              <% @conta.extratoTransferenciaOriginadas.each do |extrato| %>
              <tr class="warning">
                <td><%= extrato.conta_origem_id %></td>
                <td><%= extrato.conta_destino_id %></td>
                <td><%= extrato.created_at.strftime("%m/%d/%Y - %H:%M:%S") %></td>
                <td>R$ - <%= extrato.valor %></td>
                <td>R$ - <%= extrato.taxa %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!--  end  Context Classes  -->
  </div>
</div>
<hr>

app/views/conta/index.html.erb
<%= link_to correntista_path(current_user.correntista_id), class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>
<h2>Visualização de Contas</h2>
<p id="notice"><%= notice %></p>
<div class="row">

  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Exibição das suas Contas
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Id</th>
                <th>Correntista</th>
                <th>Conta ativa?</th>
                <th>Data de Criação</th>
                <th>Última atualização</th>
                <th>Saldo R$</th>
                <th>Ações Para Contas</th>
              </tr>
            </thead>
            <tbody>
              <% @conta.ativa.each do |conta| %>
              <tr>
                <td><%= conta.id %></td>
                <td><%= conta.correntista_id %></td>
                <td><%= conta.flag_ativo %></td>
                <td><%= conta.created_at.strftime("%m/%d/%Y - %H:%M") %></td>
                <td><%= conta.updated_at.strftime("%m/%d/%Y - %H:%M") %></td>
                <td><%= number_to_currency(conta.saldo,:format => "%u %n", :separator => ",", :delimiter => ".", :unit => "R$") %></td>
                <td>
                  <%= link_to 'Show', conta, class:"btn btn-primary" %>
                  <% if conta.saldo > 0 %>

                  <% else %>
                  <%= link_to 'Desativar Conta', correntista_conta_path(current_user.correntista_id, conta ), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

                  <% end %>
                </td>

              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conta/new.html.erb
<%= link_to correntista_path(current_user.correntista_id), class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>

<h2>Criar Nova Conta</h2>

<%= render 'form' %>

app/views/conta/show.html.erb
<%= link_to conta_index_path, class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>

<div class="row">
  <div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">
      <p id="notice"><%= notice %></p>
      <div class="text-box">
        <span class="icon-box bg-color-blue">
          <i class="fa fa-warning"></i>
        </span>
        <p class="main-text">Detalhes da Conta: <%= @conta.id  %></p>
        <hr>
      </div>
      <div class="text-box">

        <p class="text-muted">
          <span class="text-muted color-bottom-txt">
            <p>
              <strong>Id:</strong>
              <%= @conta.id %>
            </p>
          </span>
          <span class="text-muted color-bottom-txt">
            <p>
              <strong>Correntista:</strong>
              <%= @conta.correntista_id %>
            </p>
          </span>
          <span class="text-muted color-bottom-txt">

            <p>
              <strong>Flag ativo:</strong>
              <%= @conta.flag_ativo %>
            </p>
          </span>
          <span class="text-muted color-bottom-txt">

            <p>
              <strong>Data de Criação:</strong>
              <%= @conta.created_at.strftime("%m/%d/%Y - %H:%M") %>
            </p>
          </span>
          <span class="text-muted color-bottom-txt">

            <p>
              <strong>Última atualização:</strong>
              <%= @conta.updated_at.strftime("%m/%d/%Y - %H:%M:%S") %>
            </p>
          </span>
          <span class="text-muted color-bottom-txt">

            <p>
              <strong>Saldo:</strong>
              <td><%= number_to_currency(@conta.saldo,:format => "%u %n", :separator => ",", :delimiter => ".", :unit => "R$") %></td>

              <%#= @conta.saldo %>
            </p>
          </span>
        </p>

        <ul>
          <h3>Última movimentação:</h3>
          <% @conta.extratoSaque.first do |saque| %>
          <li> <%= saque.id  %>   </li>
          <li> <%= saque.valor  %>  </li>
          <li> <%= saque.created_at.strftime("%d/%m/%Y")  %>  </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>


  <div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box ">
      <span class="icon-box bg-color-red set-icon">
        <i class="fa fa-money fa-arrow-up"></i>
      </span>
      <div class="text-box">
        <% if @conta.saldo == 0 %>
        <fieldset disabled="disabled">
          <%= link_to 'Sacar', new_conta_saque_path(@conta), class:"btn btn-primary" %>
          <p class="text-muted">Lamentamos mas seu saldo é de R$ 0,00 e por isto esta função não está disponível!</p>
        </fieldset>
        <%else%>
        <%= link_to 'Sacar', new_conta_saque_path(@conta), class:"btn btn-primary" %>
        <p class="text-muted">Saque a hora que quiser, sem taxas, sem juros, saque na hora!</p>
        <%end%>

      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">
      <span class="icon-box bg-color-red set-icon">
        <i class="fa fa-envelope-o"></i>
      </span>
      <div class="text-box">
        <%= link_to 'Depositar', new_conta_deposito_path(@conta), class:"btn btn-success" %>
        <p class="text-muted">Realize depósitos rápidos e seguros para sua conta.</p>
      </div>
    </div>
  </div><div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">
      <span class="icon-box bg-color-red set-icon">
        <i class="fa fa-exchange"></i>
      </span>
      <div class="text-box">
        <%= link_to 'Transferir', transfer_new_conta_deposito_path(@conta), class:"btn btn-warning" %>
        <p class="text-muted">Faça transferências em dois cliques entre contas ou de terceiros.</p>
        <sub class="text-muted">*Transferências sujeito a Taxas, verifique aqui.</sub>
      </div>
    </div>
  </div><div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">
      <span class="icon-box bg-color-red set-icon">
        <i class="fa fa-info"></i>
      </span>
      <div class="text-box">
        <%= link_to 'Extrato', conta_extrato_path(@conta), class:"btn btn-info" %>
        <p class="text-muted">Verifique seu extrato completo ou filtrado por datas e tenha controle sobre seus ativos.</p>
      </div>
    </div>
  </div>
</div>