config/routes.rb
Rails.application.routes.draw do
  root 'info_page#home'
  get 'info_page/home'
  get 'info_page/about'

  devise_for :users

  resources :correntista do
    resources :conta
  end

  resources :conta do
    resources :saque
    resources :deposito do
      get 'transfer', on: :new
    end
    get 'extrato', :only => [:show]
  end
  resources :saque, :only => [:show]
  resources :deposito, :only => [:show]

end

app/models/correntista.rb
class Correntista < ActiveRecord::Base
  # has_one :user
  has_many :contas, :class_name => "Conta"
  validates_associated :contas

  validates_presence_of :cpf, message: ("não pode ficar em branco")
  with_options :allow_blank => false do |v|
    v.validates_presence_of :nome, message: ("não pode ficar em branco")
    v.validates_presence_of :endereco, message: ("não pode ficar em branco")
    v.validates_presence_of :bairro, message: ("Não pode ficar em branco")
    v.validates_presence_of :cidade, message: ("Não pode ficar em branco")
    v.validates_presence_of :estado, message: ("Não pode ficar em branco")
    v.validates_length_of :cpf, :is => 11, message: ("Deve ter 11 dígitos")
    v.validates_numericality_of :cpf, message:("deve conter apenas números, favor não digitar (.) e (-)"), :allow_blank => true
    v.validates_uniqueness_of :cpf, message:("já foi cadastrado anteriormente, favor verificar."), :allow_blank => true
  end

  validate :validates_as_cpf
  before_save :trataNome
  #
  # validate do |correntista|
  #   correntista.contas.each do |contas|
  #     next if contas.isvalid?
  #     contas.errors.full_messages.each do |msg|
  #       # you can customize the error message here:
  #       errors.add_to_base("Erros na Conta: #{msg}")
  #     end
  #   end
  # end


  def validates_as_cpf
    # errors.add if cpf.blank?
    # return false if cpf.nil?

    winvalidos = %w{12345678909 11111111111 22222222222 33333333333 44444444444 55555555555 66666666666 77777777777 88888888888 99999999999 00000000000}
    wvalor = cpf.scan /[0-9]/
    if wvalor.length == 11
      unless winvalidos.member?(wvalor.join)
        wvalor = wvalor.collect{|x| x.to_i}
        wsoma = 10*wvalor[0]+9*wvalor[1]+8*wvalor[2]+7*wvalor[3]+6*wvalor[4]+5*wvalor[5]+4*wvalor[6]+3*wvalor[7]+2*wvalor[8]
        wsoma = wsoma - (11 * (wsoma/11))
        wresult1 = (wsoma == 0 or wsoma == 1) ? 0 : 11 - wsoma
        if wresult1 == wvalor[9]
          wsoma = wvalor[0]*11+wvalor[1]*10+wvalor[2]*9+wvalor[3]*8+wvalor[4]*7+wvalor[5]*6+wvalor[6]*5+wvalor[7]*4+wvalor[8]*3+wvalor[9]*2
          wsoma = wsoma - (11 * (wsoma/11))
          wresult2 = (wsoma == 0 or wsoma == 1) ? 0 : 11 - wsoma
          return true if wresult2 == wvalor[10] # CPF validado
        end
      end
    end
    errors.add(:cpf, " - O CPF informado não é válido")
    # return false # CPF invalidado
  end
  def self.carregaEstados
    estado = {
      "AC" => "Acre",
      "AL" => "Alagoas",
      "AP" => "Amapá",
      "AM" => "Amazonas",
      "BA" => "Bahia",
      "CE" => "Ceará",
      "DF" => "Distrito Federal",
      "ES" => "Espírito Santo",
      "GO" => "Goiás",
      "MA" => "Maranhão",
      "MT" => "Mato Grosso",
      "MS" => "Mato Grosso do Sul",
      "MG" => "Minas Gerais",
      "PA" => "Pará",
      "PB" => "Paraíba",
      "PR" => "Paraná",
      "PE" => "Pernambuco",
      "PI" => "Piauí",
      "RJ" => "Rio de Janeiro",
      "RN" => "Rio Grande do Norte",
      "RS" => "Rio Grande do Sul",
      "RO" => "Rondônia",
      "RR" => "Roraima",
      "SC" => "Santa Catarina",
      "SP" => "São Paulo",
      "SE" => "Sergipe",
      "TO" => "Tocantins",
    }
  end

  def trataNome
    self.nome = nome.titleize
    self.nome = nome.squish
  end

end

app/controllers/correntista_controller.rb
class CorrentistaController < ApplicationController
  before_action :authenticate_user!
  before_action :set_correntista, only: [:show, :edit, :update, :destroy]

  # GET /correntista
  # GET /correntista.json
  def index
    @correntista = Correntista.all
  end

  # GET /correntista/1
  # GET /correntista/1.json
  def show
  end

  # GET /correntista/new
  def new
    @correntista = Correntista.new
  end

  # GET /correntista/1/edit
  def edit
  end

  # POST /correntista
  # POST /correntista.json
  def create
    @correntista = Correntista.new(correntista_params)
    @correntista.users_id = current_user.id
    respond_to do |format|
      if @correntista.save
        format.html { redirect_to @correntista, notice: 'Correntista was successfully created.' }
        format.json { render :show, status: :created, location: @correntista }
      else
        format.html { render :new }
        format.json { render json: @correntista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /correntista/1
  # PATCH/PUT /correntista/1.json
  def update
    respond_to do |format|
      if @correntista.update(correntista_params)
        format.html { redirect_to @correntista, notice: 'Correntista was successfully updated.' }
        format.json { render :show, status: :ok, location: @correntista }
      else
        format.html { render :edit }
        format.json { render json: @correntista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /correntista/1
  # DELETE /correntista/1.json
  def destroy
    @correntista.destroy
    respond_to do |format|
      format.html { redirect_to correntista_index_url, notice: 'Correntista was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_correntista
      @correntista = Correntista.find_by(:users_id => current_user.id)
      # @correntista = Correntista.where(:users_id => current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def correntista_params
      params.require(:correntista).permit(:id, :cpf, :nome, :datanascimento, :endereco, :numero, :bairro, :cidade, :estado)
    end
end

app/helpers/correntista_helper.rb
module CorrentistaHelper
end

app/views/correntista/_form.html.erb
<%= form_for(@correntista) do |f| %>
  <% if @correntista.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correntista.errors.count, "error") %> prohibited this correntista from being saved:</h2>

      <ul>
      <% @correntista.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!-- <%= f.label :id %><br> -->
    <%= f.hidden_field :id %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome%>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf , maxlength: 11, size: 20%>
  </div>
  <div class="field">
    <%= f.label :datanascimento %><br>
    <%= f.date_select :datanascimento, start_year: 1900 , end_year: 2005, order: [:day, :month, :year] %>

  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :bairro %><br>
    <%= f.text_field :bairro %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%#-- <%= f.text_field :estado, maxlength: 2, size: 20 %>
    <%= f.select :estado, Correntista.carregaEstados.invert, {}, {:class => "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/correntista/edit.html.erb
<%= link_to correntista_path(current_user.correntista_id), class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>
<div class="row">
  <div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">
      <h2>Editar Cadastro Correntista</h2>
      <%= render 'form' %>
    </div>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">
      <h3>Ações para seu Cadastro:</h3>
      <%= link_to @correntista, class:"btn btn-success" do %><i class="fa fa-desktop"></i> Visualizar Cadastro <% end %>
      <%#= link_to 'Show', @correntista %>
      <% link_to 'Back', correntista_index_path %>
    </div>
  </div>
</div>

app/views/correntista/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Correntista</h1>

<table>
  <thead>
    <tr>
      <th>Correntista</th>
      <th>Cpf</th>
      <th>Nome</th>
      <th>Datanascimento</th>
      <th>Endereco</th>
      <th>Numero</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @correntista.each do |correntista| %>
      <tr>
        <td><%= correntista.id %></td>
        <td><%= correntista.cpf %></td>
        <td><%= correntista.nome %></td>
        <td><%= correntista.datanascimento %></td>
        <td><%= correntista.endereco %></td>
        <td><%= correntista.numero %></td>
        <td><%= correntista.bairro %></td>
        <td><%= correntista.cidade %></td>
        <td><%= correntista.estado %></td>
        <td><%= link_to 'Show', correntista %></td>
        <td><%= link_to 'Edit', edit_correntista_path(correntista) %></td>
        <td><%= link_to 'Destroy', correntista, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Correntista', new_correntista_path %>

app/views/correntista/new.html.erb
<h1>Novo Correntista</h1>

<%= render 'form' %>

<%#= link_to 'Back', correntista_index_path %>

app/views/correntista/show.html.erb
<h2>Home:</h2>
    <p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">

      <h2>Visualizar Cadastro de correntista:</h2>

      <p>
        <strong>Correntista:</strong>
        <%= @correntista.id %>
      </p>

      <p>
        <strong>Cpf:</strong>
        <%= @correntista.cpf %>
      </p>

      <p>
        <strong>Nome:</strong>
        <%= @correntista.nome %>
      </p>

      <p>
        <strong>Datanascimento:</strong>
        <%= @correntista.datanascimento.strftime("%d/%m/%Y") %>
      </p>

      <p>
        <strong>Endereco:</strong>
        <%= @correntista.endereco %>
      </p>

      <p>
        <strong>Numero:</strong>
        <%= @correntista.numero %>
      </p>

      <p>
        <strong>Bairro:</strong>
        <%= @correntista.bairro %>
      </p>

      <p>
        <strong>Cidade:</strong>
        <%= @correntista.cidade %>
      </p>

      <p>
        <strong>Estado:</strong>
        <%= @correntista.estado %>
      </p>
      <p>
        <strong>Quantidade de Contas:</strong>
        <%= @correntista.contas.qtdAtiva %>
      </p>
    </div>
  </div>

  <div class="col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-back noti-box">
      <h3>Ações para seu Cadastro:</h3>
      <%= link_to edit_correntista_path(@correntista), class:"btn btn-primary" do %><i class="fa fa-pencil"></i> Editar Cadastro <% end %>
      <%= link_to correntista_conta_index_path(current_user), class:"btn btn-success" do %><i class="fa fa-desktop"></i> Visualizar Contas <% end %>
      <%= link_to new_correntista_conta_path(:correntista_id => @correntista.id), class:"btn btn-warning" do %><i class="fa fa-plus-square-o"></i> Criar Nova Conta <% end %>
    <%#= link_to 'Criar Conta', new_correntista_conta_path(:correntista_id => @correntista.id) %>
  </div>
</div>