config/routes.rb
Rails.application.routes.draw do
  root 'info_page#home'
  get 'info_page/home'
  get 'info_page/about'

  devise_for :users

  resources :correntista do
    resources :conta
  end

  resources :conta do
    resources :saque
    resources :deposito do
      get 'transfer', on: :new
    end
    get 'extrato', :only => [:show]
  end
  resources :saque, :only => [:show]
  resources :deposito, :only => [:show]

end

app/models/deposito.rb
require 'forwardable'
class Deposito < ActiveRecord::Base
  self.table_name = "deposito"
  has_many :conta

  scope :deposito, ->{where(conta_origem_id: nil).order(:created_at)}
  scope :transferenciaRecebidas, ->{where.not(conta_origem_id: nil).order(:created_at)}
  before_save :corrigeValor
  validates_format_of :valorProvisorio, presence: true, :with => /(?:\d*.+,)?\d+/i, :message => "Não pode ficar em branco nem ser letras. Aceita (,) ou (.)"
  after_create :depositar #entra depois de salvar

  extend Forwardable
  attr_accessor :valorProvisorio

  def corrigeValor
    self.valor = valorProvisorio.gsub(/,/){'.'}.to_d
  end
  # def corrigeValor
  #   self.valor = valorProvisorio.gsub(/,/){'.'}.to_d
  # end

  def carregaContasAivas(contaid)
    Conta.retornaContasAtivasSemContaOrigem(contaid)
  end
  #
  # def carregaContasAivas(contaid)
  #   Conta.retornaContasAtivasSemContaOrigem(contaid)
  # end
 
  def transferir
    corrigeValor
    self.taxa = acrescentaTaxa
    contaOrigem = Conta.find(self.conta_origem_id)
    contaDestino = Conta.find(self.conta_destino_id)
    valorTaxado = self.valor + self.taxa
    if consultaSaldoSuficienteContaOrigem(contaOrigem, valorTaxado)
      descontaContaOrigem(contaOrigem, valorTaxado)
      # creditaContaDestimo(contaDestino, self.valor)
    else
      errors.add(:valor, "Saldo da conta Origem é inferior ao valor a ser transferido + o valor de R$ das taxas. ")
      return false
    end
    self.save
  end

  private
  def depositar
    conta = Conta.find(self.conta_destino_id)
    conta.saldo = conta.saldo + self.valor
    conta.save
  end
  def validaValor
    if self.valor.nil?
      errors.add(:valor, "valida valor")
    end
  end


  def acrescentaTaxa
    taxa = Taxa.new
    resultado = taxa.defineTaxa(self.valor, Time.now)
    return resultado
  end

  def consultaSaldoSuficienteContaOrigem(conta, taxa)
    if (conta.saldo > taxa)
      return true
    else
      return false
    end

  end

  def descontaContaOrigem(contaOrigem, valorTaxado )
    contaOrigem.saldo -= valorTaxado
    contaOrigem.save
  end

  def creditaContaDestimo(contaDestino, valor)
    contaDestino.saldo = contaDestino.saldo + valor
    contaDestino.save
  end

  #
  # def transferir
  #   if (validaValorPorvisorio)
  #     corrigeValor
  #     self.taxa = acrescentaTaxa
  #     contaOrigem = Conta.find(self.conta_origem_id)
  #     contaDestino = Conta.find(self.conta_destino_id)
  #     valorTaxado = self.valor + self.taxa
  #     if consultaSaldoSuficienteContaOrigem(contaOrigem, valorTaxado)
  #       descontaContaOrigem(contaOrigem, valorTaxado)
  #       creditaContaDestimo(contaDestino, self.valor)
  #     else
  #       errors.add(:valor, "Saldo da conta Origem é inferior ao valor a ser transferido + o valor de R$ das taxas. ")
  #       return false
  #     end
  #   else
  #     errors.add(:valor, "O valor a ser transferido não pode ser nulo ou 0 ")
  #     return false
  #   end
  #   self.save
  #
  # end
  #
  #
  # def validaValorPorvisorio
  #   if self.valorProvisorio.blank?
  #     return false
  #   end
  #   if valorProvisorio.to_i == 0
  #     return false
  #   else
  #     return true
  #   end
  # end
  #
  # private
  # def depositar
  #
  #   conta = Conta.find(self.conta_destino_id)
  #   conta.saldo = conta.saldo + self.valor
  #   conta.save
  # end
  # def validaValor
  #   if self.valor.nil?
  #     errors.add(:valor, "valida valor")
  #   end
  # end
  #
  # private
  #
  # def acrescentaTaxa
  #   taxa = Taxa.new
  #   resultado = taxa.defineTaxa(self.valor, Time.now)
  #   return resultado
  # end
  #
  # def consultaSaldoSuficienteContaOrigem(conta, taxa)
  #   if (conta.saldo > taxa)
  #     return true
  #   else
  #     return false
  #   end
  #
  # end
  #
  # def descontaContaOrigem(contaOrigem, valorTaxado )
  #   contaOrigem.saldo -= valorTaxado
  #   contaOrigem.save!
  # end
  #
  # def creditaContaDestimo(contaDestino, valor)
  #   contaDestino.saldo = contaDestino.saldo + valor
  #   contaDestino.save!
  # end
  #

end

app/controllers/deposito_controller.rb
class DepositoController < ApplicationController
  before_action :authenticate_user!
  before_action :set_deposito, only: [:show, :edit, :update, :destroy]

  # GET /deposito
  # GET /deposito.json
  def index
    @deposito = Deposito.all
  end

  # GET /deposito/1
  # GET /deposito/1.json
  def show
  end

  # GET /deposito/new
  def new
    @deposito = Deposito.new(:conta_destino_id => params[:conta_id])
  end

  # GET /deposito/transfer
  def transfer
    @deposito = Deposito.new(:conta_origem_id => params[:conta_id])
  end

  # GET /deposito/1/edit
  def edit
  end


  # POST /deposito/transfer
  # POST /deposito/transfer.json
  def create
    @deposito = Deposito.new(deposito_params)
    respond_to do |format|
      if params[:transfer]
        if @deposito.transferir
          puts 'tete'
          format.html { redirect_to correntista_conta_index_path(current_user), notice: 'Deposito was successfully created.' }
          format.json { render :show, status: :created, location: @deposito }
        else
          format.html { render :transfer }
          format.json { render json: @deposito.errors, status: :unprocessable_entity }
        end
      else
        if @deposito.save
          format.html { redirect_to @deposito, notice: 'Deposito was successfully created.' }
          format.json { render :show, status: :created, location: @deposito }
        else
          format.html { render :new }
          format.json { render json: @deposito.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /deposito/1
  # PATCH/PUT /deposito/1.json
  def update
    respond_to do |format|
      if @deposito.update(deposito_params)
        format.html { redirect_to @deposito, notice: 'Deposito was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposito }
      else
        format.html { render :edit }
        format.json { render json: @deposito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposito/1
  # DELETE /deposito/1.json
  def destroy
    @deposito.destroy
    respond_to do |format|
      format.html { redirect_to deposito_index_url, notice: 'Deposito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_deposito
    @deposito = Deposito.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def deposito_params
    params.require(:deposito).permit(:id, :valor, :conta_destino_id, :conta_origem_id, :valorProvisorio)
  end

end

app/helpers/deposito_helper.rb
module DepositoHelper
end

app/views/deposito/_form.html.erb
<%= form_for([:conta, @deposito]) do |f| %>
  <% if @deposito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposito.errors.count, "error") %> prohibited this deposito from being saved:</h2>

      <ul>
      <% @deposito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valorProvisorio, maxlength: 18 %>
  </div>
  <div class="field">
    <%= f.label :conta_destino_id %><br>
    <%= f.text_field :conta_destino_id, :readonly => true %>
  </div>
  <div class="actions">
    <%= f.submit 'Depositar',  data: { confirm: 'Está certo dos valores?' }%>
  </div>
<% end %>

app/views/deposito/_transfer.html.erb
<%= form_for([:conta, @deposito]) do |f| %>
  <% if @deposito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposito.errors.count, "error") %> prohibited this deposito from being saved:</h2>

      <ul>
      <% @deposito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valorProvisorio, maxlength: 18 %>
  </div>
  <div class="field">
    <%= f.label :conta_origem_id %><br>
    <%= f.text_field :conta_origem_id, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :conta_destino_id %><br>
    <%= f.select :conta_destino_id, @deposito.carregaContasAivas(params[:conta_id]) %>
  </div>
  <div class="actions">
    <%= f.submit 'Transferir', :name => :transfer, data: { confirm: 'Está certo dos valores?' } %>
  </div>
<% end %>

app/views/deposito/edit.html.erb
<h1>Editing Deposito</h1>

<%= render 'form' %>

<%= link_to 'Show', @deposito %> |
<%= link_to 'Back', deposito_index_path %>

app/views/deposito/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deposito</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Valor</th>
      <th>Conta destino</th>
      <th>Conta origem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposito.each do |deposito| %>
      <tr>
        <td><%= deposito.id %></td>
        <td><%= deposito.valor %></td>
        <td><%= deposito.conta_destino_id %></td>
        <td><%= deposito.conta_origem_id %></td>
        <td><%= link_to 'Show', deposito %></td>
        <td><%= link_to 'Edit', edit_deposito_path(deposito) %></td>
        <td><%= link_to 'Destroy', deposito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposito', new_deposito_path %>

app/views/deposito/new.html.erb
<%= link_to conta_path(@deposito.conta_destino_id), class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>
<%#= link_to 'Show', conta, class:"btn btn-primary" %>


<h1>Novo Deposito</h1>

<%= render 'form' %>

<%#= link_to 'Back', deposito_index_path %>

app/views/deposito/show.html.erb
<h2>Comprovante de Depósito</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Idenfiticador:</strong>
  <%= @deposito.id %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @deposito.valor %>
</p>

<p>
  <strong>Data de criação:</strong>
  <%= @deposito.created_at.strftime("%m/%d/%Y - %H:%M:%S") %>
</p>

<p>
  <strong>Conta destino:</strong>
  <%= @deposito.conta_destino_id %>
</p>

<p>
  <strong>Conta origem:</strong>
  <%= @deposito.conta_origem_id %>
</p>
<%= link_to conta_index_path, class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>

<%#= link_to 'Edit', edit_deposito_path(@deposito) %> 
<%#= link_to 'Back', deposito_index_path %>

app/views/deposito/transfer.html.erb
<%= link_to conta_path(@deposito.conta_origem_id), class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>

<h1>Novo transfer</h1>

<%= render 'transfer' %>

<%#= link_to 'Back', deposito_index_path %>