config/routes.rb
Rails.application.routes.draw do
  root 'info_page#home'
  get 'info_page/home'
  get 'info_page/about'

  devise_for :users

  resources :correntista do
    resources :conta
  end

  resources :conta do
    resources :saque
    resources :deposito do
      get 'transfer', on: :new
    end
    get 'extrato', :only => [:show]
  end
  resources :saque, :only => [:show]
  resources :deposito, :only => [:show]

end

app/models/saque.rb
class Saque < ActiveRecord::Base

  has_many :conta
  after_validation :corrigeValor
  validate :iniciaSaque
  validates_format_of :valorProvisorio, presence: true, :with => /(?:\d*.+,)?\d+/i, :message => "Não pode ficar em branco nem ser letras. Aceita (,) ou (.)"
  # validates_presence_of :valorProvisorio, :allow_blank => false, :message => "não pode ficar em branco"

  attr_accessor :valorProvisorio
  # scope :saques, ->{order(:created_at)}

  def corrigeValor
    self.valor = self.valorProvisorio.gsub(/,/){'.'}.to_d
  end


  def iniciaSaque
    corrigeValor
    conta = Conta.find(conta_id)
    if validaSaldo(conta)
      criaSaque(conta)
    end
    # corrigeValor
    # conta = Conta.find(conta_id)
    # if (conta.saldo == 0)
    #   errors.add(:conta, "Conta está com saldo R$ 0,00." )
    # elsif (conta.saldo < self.valor)
    #   errors.add(:valor, "Valor não pode ser maior que saldo R$ em conta." )
    # end
    # conta.saldo = conta.saldo - valor
    # conta.save
  end

private
  def validaSaldo(conta)
    if (conta.saldo == 0)
      errors.add(:conta, "Conta está com saldo R$ 0,00." )
    elsif (conta.saldo < self.valor)
      errors.add(:valor, "Valor não pode ser maior que saldo R$ em conta." )
    end
    return true
  end


  def criaSaque(conta)
    conta.saldo = conta.saldo - self.valor
    conta.save!
  end
end

app/controllers/saque_controller.rb
class SaqueController < ApplicationController
  before_action :authenticate_user!
  before_action :set_saque, only: [:show, :edit, :update, :destroy]

  # GET /saque
  # GET /saque.json
  def index
    @saque = Saque.all
  end

  # GET /saque/1
  # GET /saque/1.json
  def show
  end

  # GET /saque/new
  def new
    @saque = Saque.new(:conta_id => params[:conta_id])
  end

  # GET /saque/1/edit
  def edit
  end

  # POST /saque
  # POST /saque.json
  def create
    @saque = Saque.new(saque_params)

    respond_to do |format|
      if @saque.save
        format.html { redirect_to @saque, notice: 'Saque was successfully created.' }
        format.json { render :show, status: :created, location: @saque }
      else
        format.html { render :new }
        format.json { render json: @saque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saque/1
  # PATCH/PUT /saque/1.json
  def update
    respond_to do |format|
      if @saque.update(saque_params)
        format.html { redirect_to @saque, notice: 'Saque was successfully updated.' }
        format.json { render :show, status: :ok, location: @saque }
      else
        format.html { render :edit }
        format.json { render json: @saque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saque/1
  # DELETE /saque/1.json
  def destroy
    @saque.destroy
    respond_to do |format|
      format.html { redirect_to saque_index_url, notice: 'Saque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saque
      @saque = Saque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saque_params
      params.require(:saque).permit(:valor, :created_at, :conta_id, :valorProvisorio)
    end
end

app/helpers/saque_helper.rb
module SaqueHelper
end

app/views/saque/_form.html.erb
<%= form_for([:conta, @saque]) do |f| %>
  <% if @saque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saque.errors.count, "error") %> prohibited this saque from being saved:</h2>

      <ul>
      <% @saque.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valorProvisorio, maxlength: 18  %>
  </div>


  <div class="field">
    <%= f.label :conta_id %><br>
    <%= f.text_field :conta_id, :readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit 'Sacar ',  data: { confirm: 'Está certo dos valores?' } %>
  </div>
<% end %>

app/views/saque/edit.html.erb
<h1>Editing Saque</h1>

<%= render 'form' %>

<%= link_to 'Show', @saque %> |
<%= link_to 'Back', saque_index_path %>

app/views/saque/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Saque</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Created at</th>
      <th>Time</th>
      <th>Conta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saque.each do |saque| %>
      <tr>
        <td><%= saque.valor %></td>
        <td><%= saque.created_at.strftime("%m/%d/%Y - %H:%M") %></td>
        <td><%= saque.time %></td>
        <td><%= saque.conta_id %></td>
        <td><%= link_to 'Show', saque %></td>
        <td><%= link_to 'Edit', edit_saque_path(saque) %></td>
        <td><%= link_to 'Destroy', saque, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saque', new_saque_path %>

app/views/saque/new.html.erb
<%= link_to conta_path(@saque.conta_id), class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>

<h2>Novo Saque</h2>

<%= render 'form' %>

<%#= link_to 'Back', saque_index_path %>

app/views/saque/show.html.erb
<h2>Comprovante de Saque</h2>
<p id="notice"><%= notice %></p>
<p>
  <strong>Idenfiticador:</strong>
  <%=@saque.id %>
</p>
<p>
  <strong>Valor:</strong>
  <%= @saque.valor %>
</p>

<p>
  <strong>Data de criação:</strong>
  <%= @saque.created_at.strftime("%m/%d/%Y - %H:%M:%S") %>
</p>

<p>
  <strong>Conta:</strong>
  <%= @saque.conta_id %>
</p>

<%#= link_to 'Edit', edit_saque_path(@saque) %>
<%#= link_to 'Back', conta_index_path(@saque.conta_id) %>
<%= link_to conta_index_path, class:"btn btn-default" do  %><i class="fa fa-step-backward "></i> Voltar <% end %>